name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true
      makeLatest:
        description: 'Make this the latest release'
        required: false
        default: true
      ref:
        description: 'Branch to release'
        required: true
        default: 'main'

jobs:
  upload-artifacts:
    uses: ./.github/workflows/virtual-push-artifacts.yaml
    with:
      push: true
  release:
    runs-on: ubuntu-latest
    needs: upload-artifacts
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.ref }}
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.upload-artifacts.outputs.artifact-name }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ needs.upload-artifacts.outputs.run-id }}
      - uses: ncipollo/release-action@v1
        with:
          artifacts: README.md,${{ needs.upload-artifacts.outputs.artifact-name }}
          generateReleaseNotes: true
          makeLatest: ${{ github.event.inputs.makeLatest }}
          tag: ${{ github.event.inputs.version }}
