name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true
      makeLatest:
        description: 'Make this the latest release'
        required: false
        default: true
      ref:
        description: 'Branch to release'
        required: true
        default: 'main'

jobs:
  # build:
  #   uses: ./.github/workflows/virtual-push-artifacts.yaml
  release:
    runs-on: ubuntu-latest
    # needs: build
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.ref }}
      - uses: ncipollo/release-action@v1
        with:
          artifacts: README.md
          generateReleaseNotes: true
          makeLatest: ${{ github.event.inputs.makeLatest }}
          tag: ${{ github.event.inputs.version }}
