# Push artifacts only when:
# - It's a release tag
# - It's a push to:
#   - issues/*
#   - features/*

on:
  push:
    paths:
      - '**'
      - '!.gitignore'
      - '!.devcontainer/**'
      - '!.github/workflows/**'
      - .github/workflows/log.yaml
  workflow_dispatch:

jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - name: Log
        run: |
          env | grep -v -i token

  virtual-push-artifacts:
    if: github.event_name == 'push' && (startsWith(github.ref, 'refs/tags/v') || startsWith(github.ref, 'refs/heads/issues/') || startsWith(github.ref, 'refs/heads/features/'))
    runs-on: ubuntu-latest
    needs: log
    steps:
      - name: Push artifacts
        run: echo Pushing artifacts
