# Push artifacts only when:
# - It's a release tag
# - It's a push to:
#   - issues/*
#   - features/*
name: Virtual Push Artifacts
on:
  push:
    paths:
      - '**'
      - '!.gitignore'
      - '!.devcontainer/**'
      - '!.github/workflows/**'
      - .github/workflows/virtual-push-artifacts.yaml
  workflow_dispatch:
    inputs:
      push:
        description: 'Push artifacts'
        required: true
        type: boolean
        default: 'false'
  workflow_call:
    inputs:
      push:
        description: 'Push artifacts'
        required: true
        type: boolean
    outputs:
      run-id:
        description: 'The ID of the workflow run that was triggered'
        value: ${{ github.run_id }}
      output-name:
        description: 'The name of the uploaded artifact'
        value: ${{ github.jobs.virtual-push-artifacts.outputs.output-name }}

jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - name: Log
        run: |
          env | grep -v -i token
          echo ========================================
          echo "inputs.push=${{ inputs.push }}"

  meta-should-push-artifacts:
    if: (github.event_name == 'workflow_dispatch' && inputs.push == 'true') || (github.event_name == 'push' && (startsWith(github.ref, 'refs/tags/v') || startsWith(github.ref, 'refs/heads/issues/') || startsWith(github.ref, 'refs/heads/features/')))
    runs-on: ubuntu-latest
    steps:
      - name: noop
        run: ':'

  virtual-push-artifacts:
    runs-on: ubuntu-latest
    outputs:
      output-name: output.txt
    needs:
      - log
      - meta-should-push-artifacts
    steps:
      - name: Generate artifacts
        run: echo test > output.txt
      - name: Upload artifacts
        id: upload-artifacts
        uses: actions/upload-artifact@v4
        with:
          name: output.txt
          path: output.txt

  virtual-push-other-artifacts:
    runs-on: ubuntu-latest
    needs: virtual-push-artifacts
    steps:
      - name: Push other artifacts
        run: echo Pushing other artifacts
