# Push artifacts only when:
# - It's a release tag
# - It's a push to:
#   - issues/*
#   - features/*

on:
  push:
    paths:
      - '**'
      - '!.gitignore'
      - '!.devcontainer/**'
      - '!.github/workflows/**'
      - .github/workflows/virtual-push-artifacts.yaml
  workflow_dispatch:
    inputs:
      push:
        description: 'Push artifacts'
        required: true
        type: boolean
        default: 'false'

jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - name: Log
        run: |
          env | grep -v -i token

  virtual-push-artifacts:
    if: (github.event_name == 'workflow_dispatch' && github.event.inputs.push == 'true') || (github.event_name == 'push' && (startsWith(github.ref, 'refs/tags/v') || startsWith(github.ref, 'refs/heads/issues/') || startsWith(github.ref, 'refs/heads/features/')))
    runs-on: ubuntu-latest
    needs: log
    steps:
      - name: Push artifacts
        run: echo Pushing artifacts

  virtual-push-other-artifacts:
    runs-on: ubuntu-latest
    needs: virtual-push-artifacts
    steps:
      - name: Push other artifacts
        run: echo Pushing other artifacts
